export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED',
  // DEV-36: audit append-only error codes
  AUDIT_TRANSITION_CONFLICT = 'AUDIT_TRANSITION_CONFLICT',
  AUDIT_INVALID_FIELD = 'AUDIT_INVALID_FIELD',
}
